---
apiVersion: appstream.aws.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    crossplane.io/external-name: user@example.com
    meta.upbound.io/example-id: appstream/v1beta1/userstackassociation
  labels:
    testing.upbound.io/example-name: example
  name: gitops-test-user-1
spec:
  forProvider:
    tags:
      - key: k1
        value: v1
  providerConfigRef:
    name: default

